### ISSUE TITLE
Aubergine apocalypse

### ISSUE THREAD

**Issue by mkappers** [missEnergy/veganwinners-backend#1]
HALLO!!!

IK SNAP NIET HOEVEEL AUBERGINES IK IN DE STOOFPOT MOET GOOIEN. >_> <_<

ER STAAT 3 (DRIE) KEER EEN (1) AUBERGINE IN?

- Markdown is _cool_
  - __muahahaha__
  - [Hippe link](http://veganwinners.com/recipe/5)

Groetjes,

Maurits

**Comment by missEnergy** [comment]
Hoi @mkappers !

We hebben gewerkt aan deze vervelende, hardnekkige bug, maar vooralsnog hebben we een oplossing gevonden.

We hopen dat je onze website nog vaak zult bezoeken!

Veel plezier met het bereiden van het overheerlijke stoofpotje.

Groetjes, Jasper en Ellissa
